


###################################### Time-Date ##########################################
- platform: time_date
  display_options:
     - 'time'
     - 'date'
     - 'date_time'
     - 'date_time_utc'
     - 'date_time_iso'
     - 'time_date'
     - 'time_utc'
 #    - 'beat'
##########################  UKHO Tides  ################################################################
#- platform: ukho_tides
#  api_key: d3840594de1e47e9ac32231d7f3a13db
#  stations:
#    - station_id: '0171'
#      station_name: 'Spurn Head'
#- platform: template
#  sensors:
#    next_high_tide_at:
 #  entity_id: sensor.next_high
#      friendly_name: "Next High Tide"
#      value_template: "{{as_timestamp(state_attr('sensor.spurn_head_tide', 'next_high_tide_at')) | timestamp_custom('%H:%M')}}"
#      icon_template: mdi:clock

#    next_high_tide_in:
#   entity_id: sensor.next_high_in
#      friendly_name: "Next High Tide In"
#      value_template: "{{state_attr('sensor.spurn_head_tide', 'next_high_tide_in')}}"
#      icon_template: mdi:clock

#    next_low_tide_at:
#   entity_id: sensor.next_low
#      friendly_name: "Next Low Tide"
#      value_template: "{{as_timestamp(state_attr('sensor.spurn_head_tide', 'next_low_tide_at')) | timestamp_custom('%H:%M')}}"
#      icon_template: mdi:clock
     
#    ukho_attribution:
#   entity_id: sensor.tides_attibution
#      value_template: "{{(state_attr('sensor.spurn_head_tide', 'attribution'))}}"

  
 